# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7985ae789483844fcdd7ce16e7c22275c664df0ca7b5d358447aca759a64205a877cb9c9eb649c2e0d95d4ccc13e02145ef7ca9438f38163cf41cea1b3ecd58f

test:
  secret_key_base: d678a0219563437ac09ff30c1faff0f6d0bb6ed877adf6d966b287ed0c543dde43d24ddfd6c59473e8b09dc4e8d301f1505c5c49a658bc4b4b5fa93f1ab59e5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
